export interface IconCategory {
  label: string;
  names: readonly string[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  { label: "Стрелки", names: ["ArrowBigDown", "ArrowBigDownDash", "ArrowBigLeft", "ArrowBigLeftDash", "ArrowBigRight", "ArrowBigRightDash", "ArrowBigUp", "ArrowBigUpDash", "ArrowDown", "ArrowDown01", "ArrowDown10", "ArrowDownAZ", "ArrowDownFromLine", "ArrowDownLeft", "ArrowDownNarrowWide", "ArrowDownRight", "ArrowDownToDot", "ArrowDownToLine", "ArrowDownUp", "ArrowDownWideNarrow", "ArrowDownZA", "ArrowLeft", "ArrowLeftFromLine", "ArrowLeftRight", "ArrowLeftToLine", "ArrowRight", "ArrowRightFromLine", "ArrowRightLeft", "ArrowRightToLine", "ArrowUp", "ArrowUp01", "ArrowUp10", "ArrowUpAZ", "ArrowUpDown", "ArrowUpFromDot", "ArrowUpFromLine", "ArrowUpLeft", "ArrowUpNarrowWide", "ArrowUpRight", "ArrowUpToLine", "ArrowUpWideNarrow", "ArrowUpZA", "ArrowsUpFromLine", "ChevronDown", "ChevronFirst", "ChevronLast", "ChevronLeft", "ChevronRight", "ChevronUp", "ChevronsDown", "ChevronsDownUp", "ChevronsLeft", "ChevronsLeftRight", "ChevronsLeftRightEllipsis", "ChevronsRight", "ChevronsRightLeft", "ChevronsUp", "ChevronsUpDown", "CircleArrowDown", "CircleArrowLeft", "CircleArrowOutDownLeft", "CircleArrowOutDownRight", "CircleArrowOutUpLeft", "CircleArrowOutUpRight", "CircleArrowRight", "CircleArrowUp", "CircleChevronDown", "CircleChevronLeft", "CircleChevronRight", "CircleChevronUp", "CornerDownLeft", "CornerDownRight", "CornerLeftDown", "CornerLeftUp", "CornerRightDown", "CornerRightUp", "CornerUpLeft", "CornerUpRight", "MoveDown", "MoveDownLeft", "MoveDownRight", "MoveHorizontal", "MoveLeft", "MoveRight", "MoveUp", "MoveUpLeft", "MoveUpRight", "MoveVertical", "Redo", "Redo2", "RedoDot", "SquareArrowDown", "SquareArrowDownLeft", "SquareArrowDownRight", "SquareArrowLeft", "SquareArrowOutDownLeft", "SquareArrowOutDownRight", "SquareArrowOutUpLeft", "SquareArrowOutUpRight", "SquareArrowRight", "SquareArrowUp", "SquareArrowUpLeft", "SquareArrowUpRight", "SquareChevronDown", "SquareChevronLeft", "SquareChevronRight", "SquareChevronUp", "Undo", "Undo2", "UndoDot"] },
  { label: "Медиа", names: ["Airplay", "AudioWaveform", "Camera", "CameraOff", "Cast", "Clapperboard", "Disc", "Disc2", "Disc3", "DiscAlbum", "FastForward", "Film", "Headphones", "ListMusic", "Mic", "MicOff", "MicVocal", "Music", "Music2", "Music3", "Music4", "Pause", "Play", "Podcast", "Radio", "RadioReceiver", "RadioTower", "Repeat", "Repeat1", "Repeat2", "Rewind", "Rss", "Shuffle", "SkipBack", "SkipForward", "Speaker", "Tv", "TvMinimal", "TvMinimalPlay", "Video", "VideoOff", "Videotape", "Volume", "Volume1", "Volume2", "VolumeOff", "VolumeX"] },
  { label: "Связь", names: ["AtSign", "Bell", "BellDot", "BellElectric", "BellMinus", "BellOff", "BellPlus", "BellRing", "Bluetooth", "BluetoothConnected", "BluetoothOff", "BluetoothSearching", "Forward", "Mail", "MailCheck", "MailMinus", "MailOpen", "MailPlus", "MailQuestionMark", "MailSearch", "MailWarning", "MailX", "Mailbox", "Mails", "Megaphone", "MegaphoneOff", "MessageCircle", "MessageCircleCode", "MessageCircleDashed", "MessageCircleHeart", "MessageCircleMore", "MessageCircleOff", "MessageCirclePlus", "MessageCircleQuestionMark", "MessageCircleReply", "MessageCircleWarning", "MessageCircleX", "MessageSquare", "MessageSquareCode", "MessageSquareDashed", "MessageSquareDiff", "MessageSquareDot", "MessageSquareHeart", "MessageSquareLock", "MessageSquareMore", "MessageSquareOff", "MessageSquarePlus", "MessageSquareQuote", "MessageSquareReply", "MessageSquareShare", "MessageSquareText", "MessageSquareWarning", "MessageSquareX", "MessagesSquare", "Nfc", "Phone", "PhoneCall", "PhoneForwarded", "PhoneIncoming", "PhoneMissed", "PhoneOff", "PhoneOutgoing", "Reply", "ReplyAll", "Send", "SendHorizontal", "Share", "Share2", "Signal", "SignalHigh", "SignalLow", "SignalMedium", "SignalZero", "Voicemail", "Wifi", "WifiCog", "WifiHigh", "WifiLow", "WifiOff", "WifiZero"] },
  { label: "Файлы", names: ["Archive", "ArchiveRestore", "ArchiveX", "Download", "File", "FileArchive", "FileCheck", "FileClock", "FileCode", "FileCog", "FileDown", "FileHeart", "FileImage", "FileKey", "FileLock", "FileMinus", "FileMusic", "FilePen", "FilePlay", "FilePlus", "FileSearch", "FileText", "FileUp", "FileX", "Files", "Folder", "FolderCheck", "FolderClock", "FolderClosed", "FolderCode", "FolderCog", "FolderDown", "FolderGit", "FolderHeart", "FolderKey", "FolderLock", "FolderMinus", "FolderOpen", "FolderPlus", "FolderSearch", "FolderSync", "FolderTree", "FolderUp", "FolderX", "Folders", "Import", "Package", "PackageCheck", "PackageOpen", "PackagePlus", "PackageSearch", "Save", "SaveAll", "Upload"] },
  { label: "Документы", names: ["Book", "BookA", "BookCheck", "BookDown", "BookHeart", "BookImage", "BookKey", "BookLock", "BookMarked", "BookMinus", "BookOpen", "BookOpenCheck", "BookOpenText", "BookPlus", "BookSearch", "BookText", "BookType", "BookUp", "BookUser", "BookX", "Bookmark", "BookmarkCheck", "BookmarkMinus", "BookmarkPlus", "BookmarkX", "Clipboard", "ClipboardCheck", "ClipboardClock", "ClipboardCopy", "ClipboardList", "ClipboardMinus", "ClipboardPaste", "ClipboardPen", "ClipboardPlus", "ClipboardX", "Notebook", "NotebookPen", "NotebookTabs", "NotebookText", "NotepadText", "NotepadTextDashed"] },
  { label: "Форматирование", names: ["AlignCenterHorizontal", "AlignCenterVertical", "AlignEndHorizontal", "AlignEndVertical", "AlignStartHorizontal", "AlignStartVertical", "Baseline", "Bold", "CaseLower", "CaseSensitive", "CaseUpper", "Heading", "Heading1", "Heading2", "Heading3", "Heading4", "Heading5", "Heading6", "Italic", "List", "ListCheck", "ListChecks", "ListEnd", "ListFilter", "ListMinus", "ListOrdered", "ListPlus", "ListRestart", "ListStart", "ListTodo", "ListTree", "Pilcrow", "RemoveFormatting", "Strikethrough", "Subscript", "Superscript", "TextAlignCenter", "TextAlignEnd", "TextAlignJustify", "TextAlignStart", "TextCursor", "TextQuote", "Underline"] },
  { label: "Интерфейс", names: ["AppWindow", "AppWindowMac", "Columns2", "Columns3", "Columns4", "GalleryHorizontal", "GalleryHorizontalEnd", "GalleryThumbnails", "GalleryVertical", "GalleryVerticalEnd", "Grid2x2", "Grid2x2Check", "Grid2x2Plus", "Grid2x2X", "Grid3x2", "Grid3x3", "Grip", "GripHorizontal", "GripVertical", "Layers", "Layers2", "LayersPlus", "LayoutDashboard", "LayoutGrid", "LayoutList", "LayoutPanelLeft", "LayoutPanelTop", "LayoutTemplate", "Merge", "PanelBottom", "PanelBottomClose", "PanelBottomOpen", "PanelLeft", "PanelLeftClose", "PanelLeftOpen", "PanelRight", "PanelRightClose", "PanelRightOpen", "PanelTop", "PanelTopClose", "PanelTopOpen", "Rows2", "Rows3", "Rows4", "Split", "Table", "Table2", "TableCellsMerge", "TableCellsSplit", "TableOfContents", "TableProperties", "ToggleLeft", "ToggleRight"] },
  { label: "Фигуры", names: ["Box", "Boxes", "Circle", "CircleDashed", "CircleDivide", "CircleDot", "CircleEllipsis", "CircleEqual", "CircleMinus", "CircleOff", "CircleParking", "CirclePause", "CirclePlay", "CirclePlus", "CirclePower", "CircleSlash", "CircleStop", "CircleX", "Cone", "Cylinder", "Diamond", "DiamondMinus", "DiamondPlus", "Earth", "Ellipsis", "EllipsisVertical", "Globe", "GlobeX", "Hexagon", "Octagon", "OctagonAlert", "OctagonMinus", "Pentagon", "RectangleHorizontal", "RectangleVertical", "Square", "SquareDashed", "SquareMinus", "SquarePlus", "SquareX", "Triangle", "TriangleDashed"] },
  { label: "Уведомления", names: ["BadgeAlert", "BadgeCheck", "BadgeInfo", "BadgeX", "Check", "CheckCheck", "CheckLine", "CircleAlert", "CircleCheck", "CircleCheckBig", "CircleHelp", "Info", "TriangleAlert"] },
  { label: "Безопасность", names: ["Ban", "Eye", "EyeClosed", "EyeOff", "Key", "KeyRound", "KeySquare", "Lock", "LockKeyhole", "LockKeyholeOpen", "LockOpen", "Scan", "ScanBarcode", "ScanEye", "ScanFace", "ScanHeart", "ScanLine", "ScanQrCode", "ScanSearch", "ScanText", "Shield", "ShieldAlert", "ShieldBan", "ShieldCheck", "ShieldEllipsis", "ShieldHalf", "ShieldMinus", "ShieldOff", "ShieldPlus", "ShieldUser", "ShieldX"] },
  { label: "Природа", names: ["Biohazard", "Cloud", "CloudAlert", "CloudCheck", "CloudDrizzle", "CloudFog", "CloudHail", "CloudLightning", "CloudMoon", "CloudOff", "CloudRain", "CloudRainWind", "CloudSnow", "CloudSun", "Cloudy", "Clover", "Droplets", "Eclipse", "Flame", "FlameKindling", "Flower", "Flower2", "Leaf", "LeafyGreen", "Moon", "MoonStar", "Mountain", "MountainSnow", "Rainbow", "Snowflake", "Sprout", "Sun", "SunDim", "SunMedium", "SunMoon", "Sunrise", "Sunset", "Thermometer", "ThermometerSnowflake", "ThermometerSun", "Tornado", "TreeDeciduous", "TreePalm", "TreePine", "Umbrella", "Waves", "Wind", "WindArrowDown"] },
  { label: "Животные", names: ["Beef", "Bird", "Birdhouse", "Bug", "BugOff", "Cat", "Dog", "Drumstick", "Egg", "EggFried", "EggOff", "Fish", "FishOff", "FishSymbol", "FishingHook", "Footprints", "PawPrint", "Rabbit", "Rat", "Shell", "Snail", "Squirrel", "Turtle", "Worm"] },
  { label: "Еда", names: ["Apple", "Beer", "BeerOff", "Cake", "CakeSlice", "Candy", "CandyCane", "Carrot", "ChefHat", "Cherry", "Citrus", "Coffee", "Cookie", "CookingPot", "Croissant", "Grape", "Ham", "Hamburger", "IceCreamBowl", "IceCreamCone", "Milk", "MilkOff", "Nut", "Pizza", "Popcorn", "Salad", "Sandwich", "Soup", "Utensils", "UtensilsCrossed", "Wheat", "Wine", "WineOff"] },
  { label: "Здоровье", names: ["Accessibility", "Activity", "Ambulance", "Brain", "BrainCircuit", "BrainCog", "Dna", "DnaOff", "Dumbbell", "FlaskConical", "Heart", "HeartCrack", "HeartHandshake", "HeartMinus", "HeartOff", "HeartPlus", "HeartPulse", "Microscope", "Pill", "PillBottle", "Stethoscope", "Syringe", "TestTube", "TestTubeDiagonal", "Wheelchair"] },
  { label: "Финансы", names: ["BadgeCent", "BadgeDollarSign", "BadgeEuro", "BadgeIndianRupee", "BadgeJapaneseYen", "BadgePoundSterling", "BadgeRussianRuble", "BadgeSwissFranc", "Bitcoin", "CircleDollarSign", "Coins", "CreditCard", "DollarSign", "Euro", "HandCoins", "PiggyBank", "PoundSterling", "Receipt", "ReceiptText", "ShoppingBag", "ShoppingCart", "Wallet", "WalletCards", "WalletMinimal"] },
  { label: "Аналитика", names: ["ChartArea", "ChartBar", "ChartBarBig", "ChartBarDecreasing", "ChartBarIncreasing", "ChartBarStacked", "ChartCandlestick", "ChartColumn", "ChartColumnBig", "ChartColumnDecreasing", "ChartColumnIncreasing", "ChartColumnStacked", "ChartGantt", "ChartLine", "ChartNoAxesColumn", "ChartNoAxesCombined", "ChartNoAxesGantt", "ChartPie", "ChartScatter", "ChartSpline", "Gauge", "TrendingDown", "TrendingUp", "TrendingUpDown"] },
  { label: "Пользователи", names: ["Baby", "Bot", "BotMessageSquare", "Contact", "ContactRound", "PersonStanding", "User", "UserCheck", "UserCog", "UserKey", "UserLock", "UserMinus", "UserPen", "UserPlus", "UserRound", "UserRoundCheck", "UserRoundCog", "UserRoundKey", "UserRoundMinus", "UserRoundPen", "UserRoundPlus", "UserRoundSearch", "UserRoundX", "UserSearch", "UserStar", "UserX", "Users", "UsersRound"] },
  { label: "Места", names: ["Building", "Building2", "Church", "Compass", "EarthLock", "Factory", "Fence", "Hospital", "Hotel", "House", "HouseHeart", "HousePlug", "HousePlus", "HouseWifi", "Landmark", "Library", "LibraryBig", "Map", "MapMinus", "MapPin", "MapPinCheck", "MapPinHouse", "MapPinMinus", "MapPinOff", "MapPinPen", "MapPinPlus", "MapPinX", "MapPinned", "MapPlus", "Navigation", "Navigation2", "Pyramid", "School", "Store", "Tent", "TentTree", "Warehouse"] },
  { label: "Транспорт", names: ["Anchor", "Bike", "Bus", "BusFront", "Cable", "CableCar", "Car", "CarFront", "CarTaxiFront", "Caravan", "FerrisWheel", "Forklift", "ParkingMeter", "Plane", "PlaneLanding", "PlaneTakeoff", "Rocket", "Sailboat", "Ship", "ShipWheel", "Tractor", "TrafficCone", "TrainFront", "TrainFrontTunnel", "TrainTrack", "TramFront", "Truck", "TruckElectric"] },
  { label: "Инструменты", names: ["Crop", "Drill", "Eraser", "Funnel", "FunnelPlus", "FunnelX", "Magnet", "Paintbrush", "PaintbrushVertical", "Palette", "Pen", "PenLine", "PenOff", "PenTool", "Pencil", "PencilLine", "PencilOff", "PencilRuler", "RefreshCcw", "RefreshCcwDot", "RefreshCw", "RefreshCwOff", "Rotate3d", "RotateCcw", "RotateCw", "Ruler", "Scale", "Scissors", "Search", "SearchCheck", "SearchCode", "SearchX", "Settings", "Settings2", "SlidersHorizontal", "SlidersVertical", "Wrench", "ZoomIn", "ZoomOut"] },
  { label: "Технологии", names: ["Barcode", "Battery", "BatteryCharging", "BatteryFull", "BatteryLow", "BatteryMedium", "BatteryWarning", "Code", "CodeXml", "Cpu", "Database", "DatabaseBackup", "DatabaseSearch", "DatabaseZap", "GitBranch", "GitCommitHorizontal", "GitFork", "GitGraph", "GitMerge", "GitPullRequest", "Github", "Gitlab", "HardDrive", "HardDriveDownload", "HardDriveUpload", "Joystick", "Keyboard", "Laptop", "LaptopMinimal", "MemoryStick", "Monitor", "MonitorCheck", "MonitorCog", "MonitorOff", "Mouse", "MousePointer", "MousePointerClick", "Plug", "Plug2", "PlugZap", "Power", "PowerOff", "Printer", "QrCode", "Router", "Server", "ServerCog", "ServerCrash", "Smartphone", "SmartphoneCharging", "Terminal", "Usb", "Webhook"] },
  { label: "Игры", names: ["Award", "ChessBishop", "ChessKing", "ChessKnight", "ChessPawn", "ChessQueen", "ChessRook", "Dice1", "Dice2", "Dice3", "Dice4", "Dice5", "Dice6", "Dices", "Gamepad", "Gamepad2", "GamepadDirectional", "Ghost", "Medal", "Puzzle", "Sword", "Swords", "Target", "Trophy"] },
  { label: "Время", names: ["AlarmClock", "AlarmClockCheck", "AlarmClockMinus", "AlarmClockOff", "AlarmClockPlus", "Calendar", "Calendar1", "CalendarArrowDown", "CalendarArrowUp", "CalendarCheck", "CalendarCheck2", "CalendarClock", "CalendarCog", "CalendarDays", "CalendarFold", "CalendarHeart", "CalendarMinus", "CalendarOff", "CalendarPlus", "CalendarRange", "CalendarSearch", "CalendarSync", "CalendarX", "CalendarX2", "Calendars", "Clock", "Clock1", "Clock10", "Clock11", "Clock12", "Clock2", "Clock3", "Clock4", "Clock5", "Clock6", "Clock7", "Clock8", "Clock9", "ClockAlert", "ClockArrowDown", "ClockArrowUp", "ClockCheck", "ClockPlus", "Hourglass", "Timer", "TimerOff", "TimerReset", "Watch"] },
  { label: "Взаимодействие", names: ["Copy", "CopyCheck", "CopyMinus", "CopyPlus", "CopySlash", "CopyX", "Droplet", "DropletOff", "Hand", "HandFist", "HandGrab", "HandHeart", "HandHelping", "HandMetal", "Handshake", "Lasso", "LassoSelect", "Pointer", "PointerOff", "Touchpad"] },
  { label: "Предметы", names: ["Backpack", "Badge", "BadgeMinus", "BadgePercent", "BadgePlus", "Crown", "Flashlight", "Gem", "Gift", "Glasses", "Lamp", "LampCeiling", "LampDesk", "LampFloor", "LampWallDown", "LampWallUp", "Link", "Link2", "Luggage", "Paperclip", "PartyPopper", "Shirt", "Stamp", "Sticker", "Tag", "Tags", "Ticket", "TicketCheck", "TicketMinus", "TicketPercent", "TicketPlus", "TicketX", "Tickets"] },
  { label: "Строительство", names: ["Axe", "BrickWall", "BrickWallFire", "BrickWallShield", "Construction", "HardHat", "Pickaxe", "Shovel"] },
  { label: "Другие", names: ["ALargeSmall", "AirVent", "AlarmSmoke", "Album", "Ampersand", "Amphora", "Angry", "Annoyed", "Antenna", "Anvil", "Aperture", "Armchair", "Asterisk", "Atom", "AudioLines", "BaggageClaim", "Balloon", "Barrel", "Bath", "Beaker", "Bean", "Bed", "BedDouble", "BedSingle", "BicepsFlexed", "Binary", "Binoculars", "Blend", "Blocks", "Bolt", "Bomb", "Bone", "BoomBox", "Braces", "Brackets", "Briefcase", "BriefcaseBusiness", "BriefcaseMedical", "Brush", "Calculator", "Cannabis", "Captions", "Cctv", "Cigarette", "CircuitBoard", "Club", "Cog", "Combine", "Command", "Component", "Computer", "ConciergeBell", "Container", "Contrast", "Cross", "Crosshair", "Cuboid", "CupSoda", "Currency", "Delete", "Dessert", "Diameter", "Divide", "Dock", "Donut", "DoorClosed", "DoorOpen", "Dot", "Drama", "Drone", "Drum", "Ear", "Equal", "EqualNot", "Fan", "Feather", "FireExtinguisher", "Flag", "FlagOff", "FlagTriangleLeft", "FlagTriangleRight", "FlaskRound", "FlipHorizontal", "FlipVertical", "Focus", "Frown", "Fuel", "Gavel", "GlassWater", "Goal", "GraduationCap", "Group", "Guitar", "Hash", "Haze", "Helicopter", "Highlighter", "History", "IdCard", "Image", "ImageDown", "ImageOff", "ImagePlay", "ImagePlus", "Images", "Inbox", "Infinity", "Kanban", "Laugh", "Lectern", "LifeBuoy", "Lightbulb", "LightbulbOff", "Loader", "LoaderCircle", "Locate", "LocateFixed", "LogIn", "LogOut", "Lollipop", "Maximize", "Maximize2", "Meh", "Menu", "Milestone", "Minimize", "Minimize2", "Minus", "Network", "Newspaper", "Omega", "Orbit", "Origami", "PaintBucket", "Panda", "Percent", "Pi", "Piano", "Pin", "PinOff", "Pipette", "Plus", "Pocket", "PocketKnife", "Popsicle", "Presentation", "Projector", "Quote", "Recycle", "Refrigerator", "Regex", "Replace", "Ribbon", "RockingChair", "Rose", "Route", "Satellite", "SatelliteDish", "Scaling", "ScreenShare", "Scroll", "ScrollText", "Section", "Shapes", "Sheet", "ShoppingBasket", "ShowerHead", "Shrub", "Sigma", "Signature", "Signpost", "Siren", "Skull", "Slash", "Smile", "SmilePlus", "Sofa", "SolarPanel", "Sparkle", "Sparkles", "Speech", "SpellCheck", "Spotlight", "SprayCan", "Star", "StarHalf", "StarOff", "StickyNote", "Telescope", "ThumbsDown", "ThumbsUp", "Toilet", "Toolbox", "Trash", "Trash2", "Trees", "ToyBrick", "Type", "Vault", "Vegan", "VenetianMask", "Vote", "Wand", "WandSparkles", "WashingMachine", "Webcam", "Weight", "Workflow", "X", "Zap", "ZapOff"] },
];
